version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    networks:
      - my_network
    environment:
      - SONARQUBE_HOST=sonarqube
      - SONARQUBE_PORT=9000

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092" # Puerto para Elasticsearch
    networks:
      - my_network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar

  sonarqube_db:
    image: postgres:alpine
    container_name: sonarqube_db
    networks:
      - my_network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar

networks:
  my_network:
    driver: bridge

volumes:
  jenkins_home: